# The subpath of your site. Use "" if you're hosting a blog at the root level.
baseurl: ""
# the base hostname & protocol for your site
url: "https://epstomai.github.io"
title: "广重36号 ~ 窗外的风景色"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jemoji
gems: [jekyll-paginate]
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: /blog/:title
# permalink: /blog/:year/:month/:day/:title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

theme: jekyll-theme-cayman
paginate: 15
paginate_path: "archive/page:num"
achive_path: "https://epstomai.github.io/archive/"
cur_page: "https://epstomai.github.io/archive/page:num"
